#!/usr/bin/perl
use FindBin '$Bin';

use lib $Bin;
use Nemesis;

my $Init = new Nemesis::Init();
$SIG{'INT'} = sub { $Init->sighandler(); };

use Getopt::Long qw( GetOptions );

GetOptions(
    "s=s"   => \my $SessionName,    # Session start
    "w=s"   => \my $Wrap,           # Wrap an execution script
);
$Init->io->set_debug(1);

if ( defined($Wrap) ) {
        $Init->ml()->loadmodules();

	$Init->getSession()->wrap($Wrap);
}
elsif ( defined($SessionName) ) {
    $Init->ml()->loadmodules();
	$Init->getInstance("session")->spawn($Wrap);
	$Init->getInstance("session")->wrap();
}
